### ISSUE TITLE
Unicode is not handled

### ISSUE THREAD

**Issue by christophercook** [sqmk/pecl-jsmin#14]
The following test will fail because jsmin() returns spaces (or other hidden character) where multibyte characters were originally. The original Jsmin claims to handle UTF-8 so I expected it to work here also.

--TEST--
Strings containing extended characters
--FILE--
<?php
$js = <<<JS
var test="février";
JS;
echo jsmin($js);
--EXPECT--
var test="février";

Using PHP 5.3.10 (on Ubuntu server) with a UTF-8 encoded php file I get:
var test="f vrier";

**Comment by osopolar** [comment]
Any news on that? Since I haven't used c for too log, I guess I can't help on that, but maybe this helps: http://www.cprogramming.com/tutorial/unicode.html

**Comment by c9s** [comment]
good news! #40 is now working, waiting to be merged! :)

**Comment by sqmk** [comment]
Working on new release now.

**Comment by sqmk** [comment]
Tagged as 2.0.0. Pushed release to PECL.
