### ISSUE TITLE
Plan of rolling out a new release?

### ISSUE THREAD

**Issue by c9s** [sqmk/pecl-jsmin#36]
Hi @sqmk,

Thanks for accepting the pull requests, is there a plan of rolling out a new release to PECL?

Thanks
Yo-An Lin

**Comment by sqmk** [comment]
Sure, I can release as 1.1.0. I'll attempt to do this within the next 24 hours.

**Comment by sqmk** [comment]
Release as 1.1.0.

**Comment by c9s** [comment]
Hi Michael , Thanks!
