### ISSUE TITLE
Please fix License TAG

### ISSUE THREAD

**Issue by remicollet** [sqmk/pecl-jsmin#37]
Even if the extension is PHP, it bundled jsmin.c which is (I think) MIT

So License is "PHP and MIT with exceptions"

Notice : the "The Software shall be used for Good, not Evil" make this not-free (according to FSF definition).

**Comment by sqmk** [comment]
Sounds good.

**Comment by sqmk** [comment]
MIT license allows sub-licensing. No changed necessary.

**Comment by remicollet** [comment]
This is note about MIT license, but about restrictions, which make this extension non-free, so unacceptable for most downstream distribution.

**Comment by sqmk** [comment]
Sure, I can make a note about Crockford's extension.
