### ISSUE TITLE
FEATURE REQUEST: php 5.3.x support

### ISSUE THREAD

**Issue by pine3ree** [sqmk/pecl-jsmin#45]
Hello,
this extension is indeed the fastest way to compress inline javascript in php while rendering templates. Nice port!!!

Would it be too much trouble to add back support for php 5.3.10+? I have several projects that cannot be ported to more recent versions.

I was able to compile both 2.0.0 and 2.0.1 (I am using linux anyway) of pecl-jsmin via phpize / php-config (version 5.3.29) without problems. All text succeded as well. 

Unfortunately hosting companies use PECL which only allows to install version 1.1.0 via `pecl install jsmin-1.1.0`. UTF-8 support is a must, and I would rather use this dynamic extension than php js minifiers. I did some test, with a ~ 200 lines js-code i get minification times of 50~60ms with php classes and 0.1~0.3 ms with this extension.

kind regards
maks feltrin
pine3ree

**Comment by sqmk** [comment]
I'd add back the support, but unfortunately, PHP 5.3 is EOLed.

**Comment by pine3ree** [comment]
I know...I know.... thanks anyway.
best regards
