### ISSUE TITLE
PHP 7 compilation error

### ISSUE THREAD

**Issue by accuraz** [sqmk/pecl-jsmin#47]
I'm trying to compile the feature/php7 branch but I'll get a compilation error

`/usr/local/tools/pecl-jsmin-feature-php7/utf8.c:22:10: fatal error: 'alloca.h'`
     `file not found` 
`#include <alloca.h>`
         `^`
`1 error generated.`
`*** Error code 1`

Are you aware of this ? Are you working on a fix ?

Thanks

Best,

**Comment by sqmk** [comment]
Related to #43.
