### ISSUE TITLE
Cannot compile pecl-min php7 fatal error alloca.h not found

### ISSUE THREAD

**Issue by accuraz** [sqmk/pecl-jsmin#51]
Hi,

We are trying desperately to compile pecl-min for php 7 on a FreeBSD 11 dev system.

./configure is working fine but every time we make install clean it, we have the same error 

`# make install clean
/bin/sh /usr/local/tools/pecl-jsmin/libtool --mode=compile cc  -I. -I/usr/local/tools/pecl-jsmin -DPHP_ATOM_INC -I/usr/local/tools/pecl-jsmin/include -I/usr/local/tools/pecl-jsmin/main -I/usr/local/tools/pecl-jsmin -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/tools/pecl-jsmin/utf8.c -o utf8.lo
mkdir .libs
 cc -I. -I/usr/local/tools/pecl-jsmin -DPHP_ATOM_INC -I/usr/local/tools/pecl-jsmin/include -I/usr/local/tools/pecl-jsmin/main -I/usr/local/tools/pecl-jsmin -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/tools/pecl-jsmin/utf8.c  -fPIC -DPIC -o .libs/utf8.o
/usr/local/tools/pecl-jsmin/utf8.c:22:10: fatal error: 'alloca.h' file not found
#include <alloca.h>
         ^
1 error generated.
*** Error code 1
` 

We have tested with the 2.0.1 release and we have tested with a clone of feature/php-7 branch. The compilation error above is from the feature/php7 clone with the latest commits.

Can someone help us out please ? Or can a contributor make the appropriate changes please ?

We thank you per advance for any help.

Best.

**Comment by StefanPrintezis** [comment]
#include "ext/standard/php_smart_str.h" 

php_smart_str has been changed to php_smart_string in php7

**Comment by RafalLukawiecki** [comment]
I have the same issue: trying to compile this extension for FreeBSD 11. If you or anyone else have found a solution, I would be very grateful for a hint. Thank you!

**Comment by RafalLukawiecki** [comment]
I have fixed this issue for anyone needing a FreeBSD PHP7 version of this extension. It is available in my fork of this project, see https://github.com/RafalLukawiecki/pecl-jsmin/tree/feature/php7

I have also submitted a PR #52. If and when it has been accepted and merged you will be able to use the feature/php7 branch in this repository for FreeBSD.

**Comment by sqmk** [comment]
Published on pecl as 3.0.0. Thanks @RafalLukawiecki !
